






try{

    throw new EvalError("Se ha producido un error","ejercicio13.js", 100);
} catch (err) {

    throw new EvalError(["Se ha producido un error","ejercicio13.js", 100]);
    
};
























































































/*
try{
    eval = la"S;
} catch (EvalError){
    throw new EvalError("Error de sintaxis","fichero.js",100);
}
*/